### ISSUE TITLE
let the App pull from an external JSON

### ISSUE THREAD

**Issue by TheEndiny** [TheEndiny/PalladiumApp#4]

**Comment by CommiNazi** [comment]
Implemented here: https://github.com/TheEndiny/PalladiumApp/pull/7

Right now I have it pulling from a personal S3 bucket, we'll have to find a better place for that, but it should be hosted somewhere. Can't get it from local file (I don't think, but I have to check jQuery-Mobile documentation still...), so S3 is a good option. But either way, you can change the URL in the call to wherever your file is and it will read the JSON well.
