### ISSUE TITLE
description info loops

### ISSUE THREAD

**Issue by TheEndiny** [TheEndiny/PalladiumApp#6]
the info for the first 10 spells appears to loop. For example, Befuddle (id spell-10) shows the info for Blinding Flash (id spell-1), and every ten spells loops again.

**Comment by TheEndiny** [comment]
probably the subsrt we have here? looks like it's designed to pull a digit from it instead of increment it

clicktracker = this.id;
        var details=getDetails(InvocationList[this.id.substr(-1)]);
        var tex = document.createTextNode(details);
        var el = document.createElement("DIV");
        el.id = "blah";
            el.appendChild(tex);
        $(this).append(el);

**Comment by CommiNazi** [comment]
Fixed here: https://github.com/TheEndiny/PalladiumApp/pull/7

You're correct about the issue too. 

changed from:
var details=getDetails(InvocationList[this.id.substr(-1)]);

changed to:
var details=getDetails(InvocationList[this.id.substr(this.id.indexOf("-"))]);
